development:
  adapter: postgresql
  encoding: unicode
  database: poise_development
  pool: 5
  username: jeremyideus
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: poise_test
  pool: 5
  username: jeremyideus
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: poise_production
  pool: 5
  username: jeremyideus
  password:
